const languages = {
    en: {
        home: "Home",
        bookTicket: "Book Ticket",
        cancelTicket: "Cancel Ticket",
        printTicket: "Print Ticket",
        contactUs: "Contact Us",
        language: "Language",
        title: "Prayagsamagam Boat Rides",
        experience: "Experience the Confluence of the Sacred Rivers",
        explore: "Explore the Triveni Sangam in Prayagraj with our premium boat tours.",
        bookNow: "Book Now",
        learnMore: "Learn More",
        experienceSangam: "Experience Sangam, Experience Prayagraj",
        blessed: "Prayagraj is blessed with the confluence of three rivers: Ganga, Yamuna & Saraswati. Taking a dip over Triveni Sangam, a boat-ride is necessary to reach the place where the water changes the colour and we call it SANGAM. Prayagsamagam is known for the best boat rides provider in the city.",
        threeHour: "3-Hour Boat-Ride",
        safetyJackets: "Safety Jackets",
        capacity: "Upto 7 Person Capacity",
        triveni: "Triveni Sangam",
        hanuman: "Bade Hanuman Ji Temple",
        akshaywat: "Akshaywat Temple",
        saraswati: "Saraswati Koop",
        mankameshwar: "Mankameshwar Temple",
        aboutPMA: "About PMA",
        contact: "Contact",
        hours: "Opening Hours",
        monFri: "Monday - Friday: 10am - 5pm",
        sat: "Saturday (1st & 3rd): 10am - 5pm",
        closed: "Saturday(2nd & 4th) - Sunday: Closed",
        disclaimer: "DISCLAIMER: This site contains General Information for Guidance only and Contents Provided here cannot be used for any legal Purpose",
        support: "Prayagraj, Uttar Pradesh",
        email: "support@pmaprayagraj.org.in",
        phone: "+1800 212 7745",
    },
    hi: {
        home: "मुख्य पृष्ठ",
        bookTicket: "टिकट बुक करें",
        cancelTicket: "टिकट रद्द करें",
        printTicket: "टिकट प्रिंट करें",
        contactUs: "हमसे संपर्क करें",
        language: "भाषा",
        title: "प्रयागसमागम नाव की सवारी",
        experience: "पवित्र नदियों के संगम का अनुभव करें",
        explore: "हमारे प्रीमियम नाव पर्यटन के साथ प्रयागराज में त्रिवेणी संगम का अन्वेषण करें।",
        bookNow: "अभी बुक करें",
        learnMore: "और अधिक जानें",
        experienceSangam: "संगम का अनुभव करें, प्रयागराज का अनुभव करें",
        blessed: "प्रयागराज तीन नदियों के संगम से धन्य है: गंगा, यमुना और सरस्वती। त्रिवेणी संगम में डुबकी लगाने के लिए, पानी का रंग बदलने वाले स्थान तक पहुंचने के लिए नाव की सवारी आवश्यक है जिसे हम संगम कहते हैं। प्रयागसमागम शहर में सबसे अच्छी नाव की सवारी प्रदान करने वाला है।",
        threeHour: "3-घंटे की नाव की सवारी",
        safetyJackets: "सुरक्षा जैकेट",
        capacity: "7 व्यक्ति तक की क्षमता",
        triveni: "त्रिवेणी संगम",
        hanuman: "बड़े हनुमान जी मंदिर",
        akshaywat: "अक्षयवट मंदिर",
        saraswati: "सरस्वती कूप",
        mankameshwar: "मनकामेश्वर मंदिर",
        aboutPMA: "पीएमए के बारे में",
        contact: "संपर्क",
        hours: "खुलने का समय",
        monFri: "सोमवार - शुक्रवार: 10 बजे - 5 बजे",
        sat: "शनिवार (1 और 3): 10 बजे - 5 बजे",
        closed: "शनिवार (2 और 4) - रविवार: बंद",
        disclaimer: "अस्वीकरण: यह साइट केवल मार्गदर्शन के लिए सामान्य जानकारी प्रदान करती है और यहां प्रदान की गई सामग्री का कानूनी उद्देश्य के लिए उपयोग नहीं किया जा सकता है",
        support: "प्रयागराज, उत्तर प्रदेश",
        email: "support@pmaprayagraj.org.in",
        phone: "+1800 212 7745",
    }
};
